
services:

  xiidea.easy_audit.audit_log_repository:
      class: Doctrine\Common\Persistence\ObjectRepository
      factory_service: doctrine # this is an instance of Registry
      factory_method: getRepository
      arguments: [ %xiidea.easy_audit.entity_class% ]

  xiidea.easy_audit.logger.service:
          class: Xiidea\EasyAuditBundle\Logger\Logger
          arguments: [@doctrine]
          tags:
             - { name: easy_audit.logger }

  xiidea.easy_audit.logger_factory:
          class: Xiidea\EasyAuditBundle\Logger\LoggerFactory
          public: false

  xiidea.easy_audit.event_resolver_factory:
          class: Xiidea\EasyAuditBundle\Resolver\EventResolverFactory
          public: false
          calls:
              - [ setContainer,[ @service_container ] ]

  xiidea.easy_audit.event_listener:
          class: Xiidea\EasyAuditBundle\Listener\LogEventsListener
          arguments: [@xiidea.easy_audit.logger_factory, @xiidea.easy_audit.event_resolver_factory]

  xiidea.easy_audit.prepersist_listener:
          class: %xiidea.easy_audit.pre_persist_listener%
          arguments: [%xiidea.easy_audit.entity_class% ]
          calls:
              - [ setContainer,[ @service_container ] ]
          tags:
              - { name: doctrine.event_listener, event: prePersist  }
