language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - composer selfupdate
  - composer require --prefer-source --no-interaction --dev symfony/framework-bundle:${SYMFONY_VERSION}

script: vendor/bin/phpunit
