language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
 - SYMFONY_VERSION=2.1.*
 - SYMFONY_VERSION=2.2.*
 - SYMFONY_VERSION=2.3.*
 - SYMFONY_VERSION=2.4.*
 - SYMFONY_VERSION=2.5.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - composer selfupdate
  - composer require --prefer-source --no-interaction --dev symfony/symfony:${SYMFONY_VERSION}

script: vendor/bin/phpunit
