
services:

  xiidea.easy_audit.audit_log_repository:
      class: Doctrine\Common\Persistence\ObjectRepository
      factory_service: doctrine # this is an instance of Registry
      factory_method: getRepository
      arguments: [ %xiidea.easy_audit.entity_class% ]

  xiidea.easy_audit.logger.service:
          class: Xiidea\EasyAuditBundle\Logger\Logger
          arguments: [@service_container]

  xiidea.easy_audit.default_event_resolver:
          class: Xiidea\EasyAuditBundle\Resolver\DefaultEventResolver
          arguments: [@service_container]

  default_entity_event_resolver:
          class: Xiidea\EasyAuditBundle\Resolver\EntityEventResolver
          arguments: [@service_container]

  xiidea.easy_audit.event_subscriber:
          class: Xiidea\EasyAuditBundle\Subscriber\EventsSubscriber
          arguments: [@service_container, %xiidea.easy_audit.events% ]
          tags:
              - { name: kernel.event_subscriber }

  xiidea.easy_audit.prepersist_listener:
          class: Xiidea\EasyAuditBundle\Listener\DoctrineListener
          arguments: [@service_container, %xiidea.easy_audit.entity_class% ]
          tags:
              - { name: doctrine.event_listener, event: prePersist  }
