parameters:
#    xiidea_easy_audit.example.class: Xiidea\EasyAuditBundle\Example

services:
  xiidea.easy_audit.logger.service:
          class: Xiidea\EasyAuditBundle\Logger\Logger
          arguments: [@service_container]

  xiidea.easy_audit.event.resolver.service:
          class: Xiidea\EasyAuditBundle\Event\EventResolverFactory
          arguments: [@service_container]

  xiidea.easy_audit.event_subscriber:
          class: Xiidea\EasyAuditBundle\Subscriber\EventsSubscriber
          arguments: [@service_container, %xiidea.easy_audit.events% ]
          tags:
              - { name: kernel.event_subscriber }
